apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "node.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: rabbitmq_url
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: database_url
            - name: DATABASE_LOGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: database_login
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: database_password