apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dispatcher.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dispatcher.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dispatcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dispatcher.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: rabbitmq_host
            - name: DURATION_BETWEEN_ATTEMPTS_TO_RABBITMQ
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: duration_between_attempts_to_rabbitmq
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dispatcher-secret
                  key: telegramToken